kind: pipeline
type: docker
name: arm64 Image

platform:
  os: linux
  arch: amd64

steps:
  - name: codebuild
    image: golang
    commands:
      - go build
  - name: imagebuild
    image: plugins/docker
    settings:
      repo: svilen/loki-rule-operator
      username:
        from_secret: dockerhub_username
      password:
        from_secret: docker_password
