---
kind: pipeline
type: docker
name: arm64 Image

platform:
  os: linux
  arch: arm64

steps:
  - name: create tag
    image: docker:git
    commands:
      - git fetch --tags
      - echo -n "latest-linux-arm64,$(git describe --tags --abbrev=0)-linux-arm64" > .tags # that's how one can feed tags to the docker pluging. Not very well documented tbh..
  - name: codebuild
    image: golang
    commands:
      - go mod tidy
      - go build -o loki-rule-operator
  - name: imagebuild
    image: plugins/docker
    settings:
      repo: svil/loki-rule-operator
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
---
kind: pipeline
type: docker
name: amd64 Image

platform:
  os: linux
  arch: amd64

steps:
  - name: create tag
    image: docker:git
    commands:
      - git fetch --tags
      - echo -n "latest-linux-amd64,$(git describe --tags --abbrev=0)-linux-amd64" > .tags # that's how one can feed tags to the docker pluging. Not very well documented tbh..
  - name: codebuild
    image: golang
    commands:
      - go mod tidy
      - go build -o loki-rule-operator
  - name: imagebuild
    image: plugins/docker
    settings:
      repo: svil/loki-rule-operator
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
---
kind: pipeline
type: docker
name: push manifest

steps:
  - name: manifest
    image: plugins/manifest
    settings:
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      target: svil/loki-rule-operator:latest
      template: svil/loki-rule-operator:latest-OS-ARCH
      platforms:
        - linux/amd64
        - linux/arm64
depends_on:
  - arm64 Image
  - amd64 Image
